Fixes warnings from attach terms-to-posts
wpastronaut/wp-cli-seeder pull request #1
Opened 2021-10-05 05:42 UTC by msaari

The current way the terms are attached to posts can lead to a bunch of errors:

```
Warning: array_flip() expects parameter 1 to be array, int given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_intersect_key(): Expected parameter 2 to be an array, null given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_values() expects parameter 1 to be array, null given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
```

and

```
Warning: array_flip() expects parameter 1 to be array, int given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_intersect_key(): Expected parameter 2 to be an array, null given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_values() expects parameter 1 to be array, null given in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
Warning: array_rand(): Second argument has to be between 1 and the number of elements in the array in /Users/msaari/.wp-cli/packages/vendor/wpastronaut/wp-cli-seeder/src/Attach_Command.php on line 49
```

and so on. The cause of this is the way `array_rand()` is used here. First of all, `array_rand()` expects a value between 1 and the number of elements in the array, so trying to use it with a value of 0 causes a warning and a NULL return value. So, if `mt_rand( 0, 4 )` returns zero, instead of using `array_rand()` to get a NULL value, the code should just create an empty array.

Also, when `array_rand()` returns one item from the array, it returns an int and not an array, leading to `array_flip() expects parameter 1 to be array, int given` errors.

I broke up the neat one-liner into many more lines, but now it works without errors. If the random number is over 1, the process works as before. If the random number is 1, the return value from `array_rand()` is converted to an array and if the random number is 0, an empty array is created.

2021-10-09 15:30 UTC, natanaelsinisalo commented
Thank you @msaari for such a greatly detailed PR 🙂

I'll test this by myself during the next week and will get back to you.

2021-10-14 19:15 UTC, natanaelsinisalo requested changes

2021-10-14 19:15 UTC, natanaelsinisalo commented on src/Attach_Command.php
> +			$random_term_ids = array_values( array_intersect_key( $term_ids, array_flip( $random_terms ) ) );
Technically this solution is solid, but there are a few things that could be improved to suit the existing codebase a bit better:

1. I use the short array syntax (`[]`) instead of the old one (`array()`) through the codebase. The short syntax have been in PHP since 5.4 so it's been supported long enough for me to abandon using the longer syntax completely 🙈 
2. I also usually prefer to initialize an empty array before if statement instead of creating one in an else statement. Makes the code to look a little more clean 🙃
3. I know that WordPress code style guide prefers Yoda conditionals, but using them have always felt a bit weird for me. I usually just rather use PHPCS or such to avoid forgetting to put more than one = into an if statement 😅
4. This new logic should probably be moved into a new static function into `src/Helpers.php` to make the command more readable.

So the end result would look like this

`src/Helpers.php`:
```php
public static function get_random_term_ids( $term_ids ) {
	$number_of_terms = mt_rand( 0, 4 );
	$random_terms = [];

	if( $number_of_terms === 1 ) {
		$random_terms = [array_rand( $term_ids, 1 )];
	} elseif( $number_of_terms > 1 ) {
		$random_terms = array_rand( $term_ids, $number_of_terms );
	}

	return array_values( array_intersect_key( $term_ids, array_flip( $random_terms ) ) );
}
```

`src/AttachCommand.php` line 49:
```php
$random_term_ids = Helpers::get_random_term_ids( $term_ids );
```

Would you like to commit these changes by yourself into this PR, or do you prefer me to just merge this and refactor it by myself? Both are fine for me 🙂

2021-10-15 04:31 UTC, msaari commented on src/Attach_Command.php
> +			$random_term_ids = array_values( array_intersect_key( $term_ids, array_flip( $random_terms ) ) );
Your product, your style, you can do the changes =D

2021-10-16 17:57 UTC, natanaelsinisalo commented on src/Attach_Command.php
> +			$random_term_ids = array_values( array_intersect_key( $term_ids, array_flip( $random_terms ) ) );
Sure thing, thanks for your contribution! 🙂

2021-10-16 17:57 UTC, natanaelsinisalo approved these changes

2021-10-16 17:57 UTC, merged

2021-10-16 18:13 UTC, natanaelsinisalo commented
Just released v0.5.2 which includes this fix 🙂